extends:
  - recommended-strict

plugins:
  - decorators/code-snippets.cjs

decorators:
  code-snippets/add:
    targets: [shell_curl,java_unirest,go_native,php_http2,python_python3,node_native]

rules:
  no-empty-servers: off

apis:
  vc-generator@v1:
    root: ../oas/vc-generator.yaml
    output: ../oas/dist/vc-generator.yaml