name: Deploy on GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'documentation/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: documentation

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn

      - name: Lint OAS documentation
        run: yarn oas:lint

      - name: Build the documentation
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: documentation/dist
